global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.56.12:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['192.168.56.10:9100']

  - job_name: 'apache'
    static_configs:
      - targets: ['192.168.56.11:9100']

  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.56.14:9100']

  - job_name: 'hadoop'
    static_configs:
      - targets: ['192.168.56.15:9100']